config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :items
  resources :sub_categories
  resources :categories
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services
      resources :categories
      resources :sub_categories
      resources :items

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  get '/compares', to: 'compares#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :comparisons, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
  end

  def terms
  end

  def privacy
  end
end

app/views/home/index.html.erb
<h1>Welcome to Kunthik!</h1>
<p class="lead">A reviewing platform.</p>
<br><br><br>
<%= link_to "Categories", categories_path, class: 'btn btn-primary' %>
<%= link_to "Sub Categories", sub_categories_path, class: 'btn btn-primary' %>
<%= link_to "All Items", items_path, class: 'btn btn-primary' %>

<br><br><br>
<h4>All Items</h4><br>
<div class="row">
  <% @items.each do |item| %>
    <div class="col-sm-3">
      <h5><%= link_to item.name, item_path(item) %></h5>
      <%= image_tag item.item_image.url, class: 'small-image' %>
    </div>
  <% end %>
</div>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>