config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :items
  resources :sub_categories
  resources :categories
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services
      resources :categories
      resources :sub_categories
      resources :items

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  get '/compares', to: 'compares#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :comparisons, only: [:create]
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :items

  delegate :title, to: :category, prefix: true

  mount_uploader :image, SubCategoryImageUploader
end

app/controllers/admin/sub_categories_controller.rb
module Admin
  class SubCategoriesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, except: [:index, :show]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :image, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= simple_form_for(@sub_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.association :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Edit Sub_category</h1>

<%= render 'form', sub_category: @sub_category %>

app/views/sub_categories/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Sub_categories</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_sub_category_path, class: 'btn btn-primary' do %>
    Add New Sub category
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Image</th>
            <th>Category</th>
            
      </tr>
    </thead>

    <tbody>
      <% @sub_categories.each do |sub_category| %>
        <%= content_tag :tr, id: dom_id(sub_category), class: dom_class(sub_category) do %>
          
            <td><%= link_to sub_category.name, sub_category %></td>
          

                      <td><%= image_tag sub_category.image.url, class: 'small-image' %></td>
                      <td><%= sub_category.category_title %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sub_categories/new.html.erb
<h1>New sub_category</h1>

<%= render 'form', sub_category: @sub_category %>

app/views/sub_categories/show.html.erb
<div class="page-header">
  <%= link_to sub_categories_path, class: 'btn btn-default' do %>
    All Sub_categories
  <% end %>
  <%= link_to edit_sub_category_path(@sub_category), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show sub_category</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @sub_category.name %></dd>

  <dt>Image:</dt>
  <dd><%= image_tag @sub_category.image.url, class: 'small-image' %></dd>

  <dt>Category:</dt>
  <dd><%= @sub_category.category_title %></dd>

</dl>

<p>All items of <%= @sub_category.name %></p>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Description</th>
            <th>Score</th>
            <th>Item image</th>
            <th>Sub category</th>
            <th>User</th>
            
      </tr>
    </thead>

    <tbody>
      <% @sub_category.items.each do |item| %>
        <%= content_tag :tr, id: dom_id(item), class: dom_class(item) do %>
          
            <td><%= link_to item.name, item %></td>
          

                      <td><%= item.description %></td>
                      <td><%= item.score %></td>
                      <td><%= image_tag item.item_image.url, class: 'small-image' %></td>
                      <td><%= item.sub_category_name %></td>
                      <td><%= item.user_name %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>